/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel_ideal.vistas;

import javax.swing.JOptionPane;

/**
 *
 * @author 123
 */
public class VistaGestionHabitacion extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaGestionHabitacion
     */
    public VistaGestionHabitacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbTipoDeHabitacion = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        estado = new javax.swing.JLabel();
        jtPiso = new javax.swing.JTextField();
        jrbOcupada = new javax.swing.JRadioButton();
        jbAgregar = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        jBborrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        BtBuscar = new javax.swing.JButton();
        BtLimpiar = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jButton1.setText("jButton1");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Gestion Habitacion");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Tipo de Habitacion");

        jcbTipoDeHabitacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estandar Simple", "Doble ", "Triple", "Suite Lujo" }));
        jcbTipoDeHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTipoDeHabitacionActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("N° Piso");

        estado.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        estado.setText("Estado");

        jtPiso.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jrbOcupada.setText("Ocupada");
        jrbOcupada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbOcupadaActionPerformed(evt);
            }
        });

        jbAgregar.setText("Agregar");
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        jBborrar.setText("Borrar");
        jBborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBborrarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Id Habitacion");

        jTextField1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        BtBuscar.setText("Buscar");
        BtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBuscarActionPerformed(evt);
            }
        });

        BtLimpiar.setText("Limpiar");
        BtLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Modificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBborrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtLimpiar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jrbOcupada, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtPiso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BtBuscar))
                                .addComponent(jcbTipoDeHabitacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel6)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbTipoDeHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtPiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estado)
                    .addComponent(jrbOcupada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAgregar)
                    .addComponent(jBborrar)
                    .addComponent(Modificar)
                    .addComponent(BtLimpiar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbTipoDeHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTipoDeHabitacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbTipoDeHabitacionActionPerformed

    private void jrbOcupadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbOcupadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbOcupadaActionPerformed

    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed
        // TODO add your handling code here:

//        int filaOcupadas = jtOcupadas.getSelectedRow();
//        int columnaOcupadas = jtOcupadas.getSelectedColumn();
//        int filaDesocupadas = jtDesocupadas.getSelectedRow();
//        int columnaDesocupadas = jtDesocupadas.getSelectedColumn();
//        Object datoTablaOcupadas = jtOcupadas.getValueAt(filaOcupadas, columnaOcupadas);
//        Object datoTablaDesocupadas = jtDesocupadas.getValueAt(filaDesocupadas, columnaDesocupadas);
//
//        Object seleccion = new Habitacion();
//
//        if (datoTablaOcupadas != null) {
//            seleccion = datoTablaOcupadas;
//        } else if (datoTablaDesocupadas != null) {
//            seleccion = datoTablaDesocupadas;
//        }
//
//        int piso = Integer.parseInt(jtPiso.getText());
//
//        boolean estado = jrbOcupada.isSelected();
//        if (jrbOcupada.isSelected()){
//            estado = true;
//        } else{estado=false;}
//
//        int tipoHabitacion = (int) jcbTipoDeHabitacion.getSelectedItem();

        //        Habitacion habitacion = new Habitacion(tipoHabitacion,piso,estado);
        //
        //        habitacionData.guardarHabitacion(habitacion);
        //        JtId.setText(habitacion.getId_habitacion()+"");
        //        JOptionPane.showMessageDialog(rootPane, "La Habitacion Nro "+ numero +" se guardó Correctamente");

    }//GEN-LAST:event_jbAgregarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        // TODO add your handling code here:
        //        int id_habitacion = Integer.parseInt(JtId.getText());
        //        int numero = Integer.parseInt(JtNumero.getText());
        //        int piso = Integer.parseInt(JtPiso.getText());
        //        boolean estado = Boolean.parseBoolean("true");
        //        TipoDeHabitacion tipo_de_habitacion = tipoDeHabitacionData.buscarxTipoDeHabitacion(JtTipo.getText());
        //        Habitacion habitacion=new Habitacion(id_habitacion,numero,piso,estado,tipo_de_habitacion);
        //        habitacionData.actualizarHabitacion(habitacion);
        //        //JtId.setText(habitacion.getId_habitacion()+"");
        //        JOptionPane.showMessageDialog(rootPane, "La Habitacion Nro "+ numero +" se guardó Correctamente");
    }//GEN-LAST:event_ModificarActionPerformed

    private void jBborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBborrarActionPerformed
        // TODO add your handling code here:
//        int id = Integer.parseInt(JtId.getText());
//        habitacionData.borrarHabitacion(id);
//        
//         JOptionPane.showMessageDialog(null, " La habitación se borró satisfactoriamente ");
//        
//         JtId.setText("");
//        JtNumero.setText("");
//        JtPiso.setText("");
//       jcOcupado.setSelected(false);
        
    }//GEN-LAST:event_jBborrarActionPerformed

    private void BtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBuscarActionPerformed
//        try {
            // TODO add your handling code here:
//            int id=Integer.parseInt(JtId.getText());
//            Habitacion habitacion = habitacionData.buscarHabitacion(id);
//            if (habitacion!=null) {
//                JtId.setText(habitacion.getId_habitacion()+"");
//                JtNumero.setText(habitacion.getNumero()+"");
//                JtPiso.setText(habitacion.getPiso()+"");
//                //jcOcupado.setText(habitacion.getEstado()+"");
//                if(habitacion.isEstado()){
//                    jcOcupado.setSelected(true);
//
//                }
//                cbTipo.setSelectedItem(habitacion.getTipo_de_habitacion().getTipo());
//
//                // TipoDeHabitacion tipo_de_habitacion = tipoDeHabitacionData.buscarxTipoDeHabitacion(tipo);
//
//                // cbTipo.setSelectedItem(tipo_de_habitacion);
//
//                //JtTipo.setText(habitacion.getTipo_de_habitacion().getTipo());
//            }else{
//                JOptionPane.showMessageDialog(this, "La habitacion no se encuentra cargada\n Complete los campos para agregar una nueva");
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(VistaHabitacion.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_BtBuscarActionPerformed

    private void BtLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtLimpiarActionPerformed
        // TODO add your handling code here:
//        JtId.setText("");
//        JtNumero.setText("");
//        JtPiso.setText("");
//        jcOcupado.setSelected(false);

    }//GEN-LAST:event_BtLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtBuscar;
    private javax.swing.JButton BtLimpiar;
    private javax.swing.JButton Modificar;
    private javax.swing.JLabel estado;
    private javax.swing.JButton jBborrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JComboBox<String> jcbTipoDeHabitacion;
    private javax.swing.JRadioButton jrbOcupada;
    private javax.swing.JTextField jtPiso;
    // End of variables declaration//GEN-END:variables
}
